spring:
  application:
    name: oneshop
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRATION_MILLIS}
    refresh-token-expiration-millis: ${JWT_REFRESH_TOKEN_EXPIRATION_MILLIS}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}

sitemesh:
  integration: filter
  decorator:
    prefix: /decorators/
    default: main.html
    exclusions: /css/*,/js/*,/images/*,/webjars/*,/h2-console/*,/decorators/*
    mappings:
      - path: /admin/*
        decorator: admin.html
